name = "nitro-worker"
main = "./.output/server/index.mjs"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "nitro-worker-db"
database_id = "63b24938-4a83-4a92-a096-45ba95e8dd64"

[site]
bucket = ".output/public"

[placement]
mode = "smart"